# Generated by Django 3.2.5 on 2021-07-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_shop_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
